language: python
dist: bionic

matrix:
  include:    
    - python: "2.7"
    - python: "3.4"
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"
    - python: "3.8"

before_install:
- apt-get -qq update
- apt-get install python3-pip libspatialindex-dev pybind11-dev -y -qq
- pip install pip --upgrade
- pip install setuptools
- pip install flake8 autopep8

install:
- python -c "import os,sys;assert '{}.{}'.format(*sys.version_info[:2])==os.environ['PYTHON_VERSION']"
- pip install -e .[all] 

script: 
# Check code style to the PEP 8 style guide
- autopep8 --recursive --aggressive --diff --exit-code pcg_gazebo
- autopep8 --recursive --aggressive --diff --exit-code tests
- flake8 pcg_gazebo
- flake8 tests
- python -c "import pcg_gazebo"
- pip install -e .[test]
- pytest -x tests