language: generic
sudo: required
dist: bionic

matrix:
  include:    
    - env: PYTHON_VERSION=2.7
    - env: PYTHON_VERSION=3.5
    - env: PYTHON_VERSION=3.6
    - env: PYTHON_VERSION=3.7
    - env: PYTHON_VERSION=3.8

before_install:
- sudo apt-get -qq update
- sudo apt-get install python3-pip libspatialindex-dev pybind11-dev -y -qq
- sudo pip install pip --upgrade
- sudo pip install setuptools
- sudo pip install flake8 autopep8 pytest

install:
- python -c "import os,sys;assert '{}.{}'.format(*sys.version_info[:2])==os.environ['PYTHON_VERSION']"
- pip install -e .[all] 

script: 
- autopep8 --recursive --aggressive --diff --exit-code pcg_gazebo
- flake8 pcg_gazebo
- python -c "import pcg_gazebo"
- pip install -e .[test]
- pytest -x tests