language: generic
sudo: required
dist: bionic

matrix:
  include:    
    - env: PYTHON_VERSION=3.6
    - env: PYTHON_VERSION=3.8

before_install:
- sudo apt-get -qq update
- sudo apt-get install python3-pip python3-setuptools libspatialindex-dev pybind11-dev -y -qq

install:
- pip3 install -e .

script: 
- pip3 install pytest
- python3 -c "import pcg_gazebo"
- pip3 install -e .[test]
- pytest -x tests