language: python
dist: xenial
cache: pip

matrix:
  include:    
    - python: "2.7"
    # - python: "3.4"
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"
    - python: "3.8"

before_install:
- sudo apt-get -qq update
- sudo apt-get install python3-pip libspatialindex-dev -y
- sudo pip install pip --upgrade
- sudo pip install setuptools
- sudo pip install flake8 autopep8

install:
- python -c "import sys; print(sys.version)"
- sudo pip install -e .[all] 

script: 
# Check code style to the PEP 8 style guide
- autopep8 --recursive --aggressive --diff --exit-code pcg_gazebo
- autopep8 --recursive --aggressive --diff --exit-code tests
- flake8 pcg_gazebo
- flake8 tests
- set -e; python -c "import pcg_gazebo"; set +e;
- sudo pip install -e .[test]
- pytest -x tests