language: python
dist: xenial

# Some dependencies, like python-fcl are only available 
# for 2.7 and 3.6
matrix:
  include:    
    - python: "2.7"
    - python: "3.6"
    - python: "pypy"
    - python: "pypy3"

before_install:
- sudo apt-get -qq update
- sudo apt-get install libspatialindex-dev libgeos-dev blender -y
- pip install setuptools
- pip install flake8 autopep8

install:
- python -c "import sys; print(sys.version)"
- pip install -e .[all] 

script: 
# Check code style to the PEP 8 style guide
- autopep8 --recursive --aggressive --diff --exit-code pcg_gazebo
- autopep8 --recursive --aggressive --diff --exit-code tests
- flake8 pcg_gazebo
- flake8 tests
# Test importing the package
- set -e; python -c "import pcg_gazebo"; set +e;
# Install test dependencies and run tests
- pip install -e .[test]
- pytest -x tests