name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        sudo apt-get -qq update
        sudo apt-get install libspatialindex-dev pybind11-dev -y -qq
    - name: Lint with flake8
      run: |
        pip install flake8 autopep8
        # stop the build if there are Python syntax errors or undefined names
        flake8 pcg_gazebo
        flake8 tests
        autopep8 --recursive --aggressive --diff --exit-code pcg_gazebo
        autopep8 --recursive --aggressive --diff --exit-code tests        
    - name: Install package
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        python -c "import pcg_gazebo"
    - name: Test with pytest
      run: |
        pip install pytest
        pip install -e .[test]
        pytest
