name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
        matrix:      
          python-version: [2.7, 3.6, 3.7]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1            
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: Install dependencies
      run: |
        sudo apt-get -qq update
        sudo apt-get install libspatialindex-dev pybind11-dev libgeos-dev -y -qq
    - name: Lint with flake8
      run: |
        pip install flake8 autopep8
        # stop the build if there are Python syntax errors or undefined names
        flake8 pcg_gazebo
        flake8 scripts
        flake8 tests
        autopep8 --recursive --aggressive --diff --exit-code pcg_gazebo
        autopep8 --recursive --aggressive --diff --exit-code scripts
        autopep8 --recursive --aggressive --diff --exit-code tests        
    - name: Install package
      run: |
        python -m pip install --upgrade pip
        pip install -e .[test]
        python -c "import pcg_gazebo"
    - name: Test with pytest
      run: |
        pytest
    - name: Prepare package for deployment
      if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags') && matrix.python-version == 3.6
      run: |
        pip install twine wheel
        python setup.py sdist bdist_wheel
        twine check dist/*
    - name: Publish package
      if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags') && matrix.python-version == 3.6
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: ${{ secrets.PYPI_USERNAME }}
        password: ${{ secrets. PYPI_PASSWORD }}
